import { readFileSync } from "node:fs";
import prettier from "prettier";

const $package = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
);
const lVersionSource = await prettier.format(
  `// generated by tools/get-version.ts - edits will be overwritten\nexport const VERSION = "${$package.version}";\n`,
  {
    parser: "babel",
  },
);
process.stdout.write(lVersionSource);
