name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
      - "*/**.yml"
  pull_request:
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
      - "*/**.yml"
  workflow_dispatch:

env:
  CI: true
  NODE_LATEST: 22.x

defaults:
  run:
    shell: bash

jobs:
  check:
    name: check
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm run build
      - run: npm run depcruise -- --no-cache --progress performance-log
        if: always() && matrix.node-version != '20.x'
      - run: npm test
        if: always() && matrix.node-version != '20.x'
      - name: run test & emit results to step summary
        # code coverage report on 20.x only, as --experimental-test-coverage on node 22.x is not stable
        # (gives varying results over identical runs)
        if: always() && matrix.node-version == '20.x'
        run: |
          echo '## Code coverage' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npm test >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: on pushes to the default branch emit full depcruise results to step summary
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: |
          yarn --silent depcruise --output-type markdown >> $GITHUB_STEP_SUMMARY
          echo '## Visual overview' >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          yarn --silent depcruise --exclude ".test.ts$" --include-only "^(src)" --output-type mermaid >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: on pull requests emit depcruise results + diff graph to step summary
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'pull_request' && github.ref_name != github.event.repository.default_branch
        run: |
          yarn --silent depcruise --output-type markdown >> $GITHUB_STEP_SUMMARY
          echo '## Visual diff' >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          SHA=${{github.event.pull_request.base.sha}} yarn --silent depcruise:graph:diff:mermaid >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
