name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
      - "*/**.yml"
  pull_request:
    paths-ignore:
      - "*/**.md"
      - "*/**.txt"
      - "*/**.yml"
  workflow_dispatch:

env:
  CI: true
  NODE_LATEST: 24.x

defaults:
  run:
    shell: bash

jobs:
  check:
    name: check
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 18.x
          - 24.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: remove .npmrc on node 18 so that the npm install works
        # e.g. lint-staged doesn't work with node 18 anymore, but we don't need it
        # on the ci and hence don't want it to block the ci run. By removing the .npmrc
        # engine-strict = true isn't enforced anymore, and the install will still work
        # the other stuff in .npmrc is still relevant, so se set it with npm config.
        if: matrix.node-version == '18.x'
        run: |
          rm -f .npmrc
          npm config set package-lock=true
          npm config set save-exact=true
      - run: npm install
      - run: npm run build
      - run: npm run depcruise -- --no-cache --progress performance-log
      - run: npm test
      - name: emit coverage results to step summary
        if: always() && matrix.node-version == env.NODE_LATEST
        run: |
          echo '## Code coverage' >> $GITHUB_STEP_SUMMARY
          npx tsx tools/istanbul-json-summary-to-markdown.ts < coverage/coverage-summary.json >> $GITHUB_STEP_SUMMARY
      - name: on pushes to the default branch emit full depcruise results to step summary
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: |
          yarn --silent depcruise --output-type markdown >> $GITHUB_STEP_SUMMARY
          echo '## Visual overview' >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          yarn --silent depcruise --exclude ".test.ts$" --include-only "^(src)" --output-type mermaid >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: on pull requests emit depcruise results + diff graph to step summary
        if: always() && matrix.node-version == env.NODE_LATEST && github.event_name == 'pull_request' && github.ref_name != github.event.repository.default_branch
        run: |
          yarn --silent depcruise --output-type markdown >> $GITHUB_STEP_SUMMARY
          echo '## Visual diff' >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          SHA=${{github.event.pull_request.base.sha}} yarn --silent depcruise:graph:diff:mermaid >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
